// compare formPage

export const validateFields = {
  formPage: ['name', 'formQuestionTypeCategoryId', 'isActive', 'pageIndex', 'formPageGroupGuid', 'formPageGroupName'],
  formPageGroups: ['name', 'id'],
  formQuestion: [
    'isScore',
    'labelTo',
    'uid',
    'isAllowComment',
    'id',
    'questionType',
    'groupCode',
    'description',
    'isIncludeTime',
    'remoteId',
    'labelFrom',
    'isMultiAnswer',
    'formPageGuid',
    'isMandatory',
    'guid',
    'isImage',
    'isActive',
    'formPageId',
    'isRequiredLocation',
    'formQuestionTypeId',
    'isDeclareQuantity',
    'isDeclareQuantityMandatory',
    'budgetCode',
    'projectTypeId',
  ],
  formQuestionAnswer: ['id', 'label', 'uid', 'value', 'formQuestionAnswerTemplateId'],
  formUserAnswer: ['formGuid', 'formId', 'isActive', 'pageIndex'],
  formUserAnswerQuestion: [
    'uaqComment',
    'uaqAnswerContent',
    'uaqAnswerNumeric',
    'uaqAnswerDate',
    'uaqDeclareQuantity',
    'uaqDefectDescription',
    'isDefect',
  ],
  formUserAnswerQuestionImage: [
    'location',
    'uid',
    'workflowGuid',
    'position',
    'path',
    'longitude',
    'files',
    'latitude',
  ],
  formUserAnswerQuestionOption: ['id', 'label', 'uid', 'value', 'formQuestionAnswerTemplateId'],
  formUserAnswerQuestionMarching: [
    'uaqMarchingId',
    'uaqAnswerIsPhotographTaken',
    'uaqAnswerMarching',
    'uaqAnswerTexts',
  ],
  formSubQuestion: ['id', 'description', 'isDescriptionDefined', 'formQuestionTypeId', 'uaqAnswerContent'],
  formSubQuestionAnswer: ['id', 'description'],
  formSubUserAnswerQuestion: ['id', 'uaqAnswerContent', 'uaqAnswerNumeric', 'uaqComment'],
  formSubUserAnswerQuestionOption: ['id', 'uaqId'],
};
