/* eslint-disable global-require */
import _ from 'lodash';
import { isSIBundleID } from '../Config';

export default {
  IC_Close: require('../Resources/icon/close.png'),
  IC_ERROR_MODAL: require('../Resources/icon/thumbnail_noun_Error.png'),
  IC_CloseWhite: require('../Resources/icon/close-white.png'),
  IC_Clip_Board: require('../Resources/icon/copy-content.png'),
  IC_ArrowRight: require('../Resources/icon/arrowRight.png'),
  IC_Backdark: require('../Resources/icon/back-blue.png'),
  IC_Bell: require('../Resources/icon/bell.png'),
  IC_Calendar: require('../Resources/icon/calendar.png'),
  IC_Chat: require('../Resources/icon/chat.png'),
  IC_CheckTask: require('../Resources/icon/checkTask.png'),
  IC_User: require('../Resources/icon/user.png'),
  IC_InvertedTriangle: require('../Resources/icon/InvertedTriangle.png'),
  IC_Plus: require('../Resources/icon/plus.png'),
  IC_Search: require('../Resources/icon/search.png'),
  IC_SettingWhite: require('../Resources/icon/setting-white.png'),
  IC_AddImage: require('../Resources/icon/AddImage.png'),
  IC_PlusWhite: require('../Resources/icon/plusWhite.png'),
  IC_Filter: require('../Resources/icon/filter-icon.png'),
  IC_Filter_White: require('../Resources/icon/filter_white.png'),
  IC_Checked: require('../Resources/icon/checked.png'),
  IC_DeleteImage: require('../Resources/icon/deleteImage.png'),
  IC_WarningModal: require('../Resources/icon/WarrningModal.png'),
  IC_SuccessModal: require('../Resources/icon/success.png'),
  IC_ChatWO: require('../Resources/icon/chatWO.png'),
  IC_Send: require('../Resources/icon/send.png'),
  IC_SendWhite: require('../Resources/icon/sendWhite.png'),
  IC_Require: require('../Resources/icon/require.png'),
  IC_WO: require('../Resources/icon/WO.png'),
  IC_QR_CODE: require('../Resources/icon/qr-code.png'),
  IC_DL: require('../Resources/icon/DL.png'),
  IC_CHECK: require('../Resources/icon/Check.png'),
  IC_TASK: require('../Resources/icon/Task.png'),
  IC_PROPERTY_INSPECTON: require('../Resources/icon/PropertyInspection.png'),
  IC_IN_OUT_LIST: require('../Resources/icon/ic_in_out.png'),
  IC_SURVEY: require('../Resources/icon/survey.png'),
  IC_EMPLOYEE_SURVEY: require('../Resources/icon/employee-survey.png'),
  IC_VOLTAGE: require('../Resources/icon/voltage.png'),

  IC_INVENTORY: require('../Resources/icon/IC_Inventory.png'),
  IC_PLAN: require('../Resources/icon/IC_PLAN.png'),

  IC_Phone: require('../Resources/icon/phone.png'),
  IC_Mail: require('../Resources/icon/mail.png'),
  IC_Currency: require('../Resources/icon/currency.png'),
  IC_Building: require('../Resources/icon/ic_building.png'),

  IC_arrow_up_white: require('../Resources/icon/ic_arrow_up_white.png'),
  IC_arrow_up_blue: require('../Resources/icon/ic_arrow_up_blue.png'),
  IC_arrow_down_blue: require('../Resources/icon/ic_arrow_down_blue.png'),
  IC_arrow_down_white: require('../Resources/icon/ic_arrow_down_white.png'),

  IC_checkIn: require('../Resources/icon/CheckInGreen.png'),
  IC_checkOut_white: require('../Resources/icon/checkOutMap.png'),
  IC_checkIn_white: require('../Resources/icon/checkInWhite.png'),
  IC_checkOut: require('../Resources/icon/checkOutGreen.png'),
  IC_RECEIPT: require('../Resources/icon/receipt.png'),
  IC_In_Out: require('../Resources/icon/icon_in_out.png'),

  IC_checkBox: require('../Resources/icon/check-box.png'),
  IC_checkedBox: require('../Resources/icon/checked-box.png'),
  IC_createBy: require('../Resources/icon/create_by.png'),
  IC_lock: require('../Resources/icon/lock.png'),
  IC_location: require('../Resources/icon/locationIcon.png'),

  IC_camera: require('../Resources/icon/ic_camera.png'),
  IC_noti_setting: require('../Resources/icon/notify_setting.png'),
  IC_mail_setting: require('../Resources/icon/mail_setting.png'),

  ic_check_form: require('../Resources/icon/check_form.png'),
  ic_checked_form: require('../Resources/icon/checked_fee.png'),
  ic_star_form: require('../Resources/icon/Star.png'),
  ic_star_selected_form: require('../Resources/icon/Star-big.png'),
  signatureIcon: require('../Resources/icon/signature-icon.png'),
  IC_SHADOW_WHITE_PLUS: require('../Resources/icon/shadow-white-plus.png'),
  IC_BACK_BLUE: require('../Resources/icon/back-blue.png'),
  IC_SEARCH_BLUE: require('../Resources/icon/search-blue.png'),
  IC_EDIT: require('../Resources/icon/edit-icon.png'),
  IC_SAVE: require('../Resources/icon/save-icon.png'),
  IC_SUCCESS: require('../Resources/icon/success-icon.png'),
  IC_TAB_FORM: require('../Resources/icon/tab-form.png'),
  IC_TAB_HOME: require('../Resources/icon/tab-home.png'),
  IC_TAB_PROPERTY: require('../Resources/icon/tab-property.png'),
  IC_TAB_SYNC: require('../Resources/icon/tab-sync.png'),
  IC_FINGER_PRINT: require('../Resources/icon/finger-print.png'),
  IC_FACE_ID: require('../Resources/icon/face-id.png'),

  IMG_ChatEmty: require('../Resources/image/chat-emty.png'),
  IMG_AvatarDefault: require('../Resources/image/avatar-default.png'),
  IMG_ChooseProject: require('../Resources/image/ChooseProject.png'),
  IMG_ImgLogin: require('../Resources/image/imgLogin.png'),
  IMG_Logo: require('../Resources/image/property_cube.png'),
  IMG_SplashScreen: isSIBundleID
    ? require('../Resources/image/splash_screen.png')
    : require('../Resources/image/splash_screen_hub.png'),
  IMG_EmtyWorkoder: require('../Resources/image/emtyWorkoder.png'),
  IMG_EmptyImage: require('../Resources/image/empty-image.jpg'),
  IMG_EmptyList: require('../Resources/image/empty-list.png'),
  IMG_LIBRARY_EMPTY: require('../Resources/image/libary-emty.png'),
  IMG_INSPECTION_PROPERTY: require('../Resources/image/inspection-property.png'),
  IMG_LOGIN_BACKGROUND: require('../Resources/image/login-background.png'),
  IMG_LIBRARY_IMAGE: require('../Resources/image/ImageLibary.png'),
  IMG_LIBRARY_PDF: require('../Resources/image/PDFLibary.png'),
  IMG_LIBRARY_VIDEO: require('../Resources/image/VIDEOLibary.png'),
  IMG_LIBRARY_DEFAULT: require('../Resources/image/defaultLibary.png'),
  IC_SEND_BY_EMAIL: require('../Resources/icon/ic-send-email.png'),
  IC_SEND_BY_PHONE: require('../Resources/icon/ic-send-phone.png'),
};
